// Private synthetic fixture to exercise offline .xlsx decoding; not distributed to end user.
const JSZip=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/pptxgenjs/node_modules/jszip');
const zip=new JSZip();const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
zip.file('xl/workbook.xml','<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="ورقة أولى" sheetId="1" r:id="rId1"/><sheet name="دفتر العمليات" sheetId="2" r:id="rId2"/></sheets></workbook>');
zip.file('xl/_rels/workbook.xml.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Target="worksheets/sheet1.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"/><Relationship Id="rId2" Target="/xl/worksheets/sheet2.xml" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"/></Relationships>');
const letter=i=>String.fromCharCode(65+i);const row=(values,num)=>`<row r="${num}">${values.map((val,i)=>typeof val==='number'?`<c r="${letter(i)}${num}"><v>${val}</v></c>`:`<c r="${letter(i)}${num}" t="inlineStr"><is><t>${esc(val)}</t></is></c>`).join('')}</row>`;
const worksheet=rows=>'<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>'+rows.map((r,i)=>row(r,i+1)).join('')+'</sheetData></worksheet>';
zip.file('xl/worksheets/sheet1.xml',worksheet([['اسم','قيمة'],['تجريبي',1]]));
const excelDate=Math.round((Date.UTC(2026,8,12)-Date.UTC(1899,11,30))/86400000);
zip.file('xl/worksheets/sheet2.xml',worksheet([['التاريخ','البيان','المبلغ','رقم المستند','نوع العملية'],[excelDate,'شراء أدوات',125.750,'A-8','مصروف'],[excelDate,'مبيعات',320,'S-8','إيراد']]));
zip.file('[Content_Types].xml','<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="xml" ContentType="application/xml"/><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>');
zip.generateAsync({type:'nodebuffer'}).then(x=>require('fs').writeFileSync('/tmp/sanad-test.xlsx',x));
